# Generated by Django 5.0.1 on 2024-01-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Product Category",
                "db_table": "product_category",
            },
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "Storable"),
                            ("consu", "Consumable"),
                            ("services", "Services"),
                        ],
                        max_length=200,
                    ),
                ),
                ("cost", models.IntegerField()),
                ("price", models.IntegerField()),
                ("description", models.TextField(max_length=350)),
                ("ref", models.CharField(max_length=50)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Template",
                "db_table": "product_template",
            },
        ),
    ]
